// Generated by the private Deucarian Brand scripts/generate_tokens.py. Do not edit.
// This is a versioned value snapshot and has no runtime dependency on Deucarian Brand.
using Deucarian.Theming;
using UnityEngine;

namespace Deucarian.Theming.Editor
{
    public static class DeucarianBrandThemePreset
    {
        public const string Version = "0.1.0-concept.2";

        public static class Light
        {
            // deucarian.background <- semantic.color.canvas
            public static readonly Color32 Background = new Color32(0xF6, 0xF8, 0xFA, 0xFF);
            // deucarian.surface <- semantic.color.surface.default
            public static readonly Color32 Surface = new Color32(0xFF, 0xFF, 0xFF, 0xFF);
            // deucarian.surface.raised <- semantic.color.surface.raised
            public static readonly Color32 SurfaceRaised = new Color32(0xFF, 0xFF, 0xFF, 0xFF);
            // deucarian.primary <- semantic.color.brand.primary
            public static readonly Color32 Primary = new Color32(0x17, 0x43, 0x67, 0xFF);
            // deucarian.secondary <- semantic.color.accent.teal
            public static readonly Color32 Secondary = new Color32(0x0B, 0x6B, 0x68, 0xFF);
            // deucarian.accent <- semantic.color.accent.amber
            public static readonly Color32 Accent = new Color32(0x9A, 0x5A, 0x0A, 0xFF);
            // deucarian.text.primary <- semantic.color.text.primary
            public static readonly Color32 TextPrimary = new Color32(0x0B, 0x11, 0x17, 0xFF);
            // deucarian.text.secondary <- semantic.color.text.secondary
            public static readonly Color32 TextSecondary = new Color32(0x26, 0x34, 0x42, 0xFF);
            // deucarian.text.muted <- semantic.color.text.muted
            public static readonly Color32 TextMuted = new Color32(0x52, 0x60, 0x6D, 0xFF);
            // deucarian.text.disabled <- semantic.color.text.disabled
            public static readonly Color32 TextDisabled = new Color32(0x89, 0x97, 0xA5, 0xFF);
            // deucarian.success <- semantic.color.status.success
            public static readonly Color32 Success = new Color32(0x0B, 0x6B, 0x68, 0xFF);
            // deucarian.warning <- semantic.color.status.warning
            public static readonly Color32 Warning = new Color32(0x9A, 0x5A, 0x0A, 0xFF);
            // deucarian.error <- semantic.color.status.error
            public static readonly Color32 Error = new Color32(0x9F, 0x24, 0x1A, 0xFF);
            // deucarian.info <- semantic.color.status.info
            public static readonly Color32 Info = new Color32(0x1E, 0x5F, 0x8D, 0xFF);
            // deucarian.ui.normal <- semantic.color.surface.default
            public static readonly Color32 UiNormal = new Color32(0xFF, 0xFF, 0xFF, 0xFF);
            // deucarian.ui.highlighted <- semantic.color.surface.raised
            public static readonly Color32 UiHighlighted = new Color32(0xFF, 0xFF, 0xFF, 0xFF);
            // deucarian.ui.pressed <- semantic.color.brand.primary
            public static readonly Color32 UiPressed = new Color32(0x17, 0x43, 0x67, 0xFF);
            // deucarian.ui.selected <- semantic.color.accent.teal
            public static readonly Color32 UiSelected = new Color32(0x0B, 0x6B, 0x68, 0xFF);
            // deucarian.ui.disabled <- semantic.color.border.subtle
            public static readonly Color32 UiDisabled = new Color32(0xD7, 0xDE, 0xE5, 0xFF);
            // deucarian.ui.focused <- semantic.color.focusRing
            public static readonly Color32 UiFocused = new Color32(0x1E, 0x5F, 0x8D, 0xFF);
        }

        public static class Dark
        {
            // deucarian.background <- semantic.color.canvas
            public static readonly Color32 Background = new Color32(0x07, 0x11, 0x1F, 0xFF);
            // deucarian.surface <- semantic.color.surface.default
            public static readonly Color32 Surface = new Color32(0x0B, 0x1A, 0x2C, 0xFF);
            // deucarian.surface.raised <- semantic.color.surface.raised
            public static readonly Color32 SurfaceRaised = new Color32(0x10, 0x2B, 0x46, 0xFF);
            // deucarian.primary <- semantic.color.brand.primary
            public static readonly Color32 Primary = new Color32(0x87, 0xBD, 0xD7, 0xFF);
            // deucarian.secondary <- semantic.color.accent.teal
            public static readonly Color32 Secondary = new Color32(0x64, 0xC1, 0xB6, 0xFF);
            // deucarian.accent <- semantic.color.accent.amber
            public static readonly Color32 Accent = new Color32(0xF0, 0xBC, 0x69, 0xFF);
            // deucarian.text.primary <- semantic.color.text.primary
            public static readonly Color32 TextPrimary = new Color32(0xF6, 0xF8, 0xFA, 0xFF);
            // deucarian.text.secondary <- semantic.color.text.secondary
            public static readonly Color32 TextSecondary = new Color32(0xED, 0xF1, 0xF4, 0xFF);
            // deucarian.text.muted <- semantic.color.text.muted
            public static readonly Color32 TextMuted = new Color32(0xD7, 0xDE, 0xE5, 0xFF);
            // deucarian.text.disabled <- semantic.color.text.disabled
            public static readonly Color32 TextDisabled = new Color32(0x52, 0x60, 0x6D, 0xFF);
            // deucarian.success <- semantic.color.status.success
            public static readonly Color32 Success = new Color32(0x64, 0xC1, 0xB6, 0xFF);
            // deucarian.warning <- semantic.color.status.warning
            public static readonly Color32 Warning = new Color32(0xF0, 0xBC, 0x69, 0xFF);
            // deucarian.error <- semantic.color.status.error
            public static readonly Color32 Error = new Color32(0xFF, 0xB4, 0xAB, 0xFF);
            // deucarian.info <- semantic.color.status.info
            public static readonly Color32 Info = new Color32(0x87, 0xBD, 0xD7, 0xFF);
            // deucarian.ui.normal <- semantic.color.surface.default
            public static readonly Color32 UiNormal = new Color32(0x0B, 0x1A, 0x2C, 0xFF);
            // deucarian.ui.highlighted <- semantic.color.surface.raised
            public static readonly Color32 UiHighlighted = new Color32(0x10, 0x2B, 0x46, 0xFF);
            // deucarian.ui.pressed <- semantic.color.brand.primary
            public static readonly Color32 UiPressed = new Color32(0x87, 0xBD, 0xD7, 0xFF);
            // deucarian.ui.selected <- semantic.color.accent.teal
            public static readonly Color32 UiSelected = new Color32(0x64, 0xC1, 0xB6, 0xFF);
            // deucarian.ui.disabled <- semantic.color.border.subtle
            public static readonly Color32 UiDisabled = new Color32(0x17, 0x43, 0x67, 0xFF);
            // deucarian.ui.focused <- semantic.color.focusRing
            public static readonly Color32 UiFocused = new Color32(0x87, 0xBD, 0xD7, 0xFF);
        }

        public static bool TryGetColor(DeucarianThemeMode mode, string roleId, out Color color)
        {
            if (mode == DeucarianThemeMode.Light)
            {
                return TryGetLightColor(roleId, out color);
            }

            if (mode == DeucarianThemeMode.Dark)
            {
                return TryGetDarkColor(roleId, out color);
            }

            color = default(Color);
            return false;
        }

        private static bool TryGetLightColor(string roleId, out Color color)
        {
            switch (roleId)
            {
                case "deucarian.background":
                    color = Light.Background;
                    return true;
                case "deucarian.surface":
                    color = Light.Surface;
                    return true;
                case "deucarian.surface.raised":
                    color = Light.SurfaceRaised;
                    return true;
                case "deucarian.primary":
                    color = Light.Primary;
                    return true;
                case "deucarian.secondary":
                    color = Light.Secondary;
                    return true;
                case "deucarian.accent":
                    color = Light.Accent;
                    return true;
                case "deucarian.text.primary":
                    color = Light.TextPrimary;
                    return true;
                case "deucarian.text.secondary":
                    color = Light.TextSecondary;
                    return true;
                case "deucarian.text.muted":
                    color = Light.TextMuted;
                    return true;
                case "deucarian.text.disabled":
                    color = Light.TextDisabled;
                    return true;
                case "deucarian.success":
                    color = Light.Success;
                    return true;
                case "deucarian.warning":
                    color = Light.Warning;
                    return true;
                case "deucarian.error":
                    color = Light.Error;
                    return true;
                case "deucarian.info":
                    color = Light.Info;
                    return true;
                case "deucarian.ui.normal":
                    color = Light.UiNormal;
                    return true;
                case "deucarian.ui.highlighted":
                    color = Light.UiHighlighted;
                    return true;
                case "deucarian.ui.pressed":
                    color = Light.UiPressed;
                    return true;
                case "deucarian.ui.selected":
                    color = Light.UiSelected;
                    return true;
                case "deucarian.ui.disabled":
                    color = Light.UiDisabled;
                    return true;
                case "deucarian.ui.focused":
                    color = Light.UiFocused;
                    return true;
                default:
                    color = default(Color);
                    return false;
            }
        }

        private static bool TryGetDarkColor(string roleId, out Color color)
        {
            switch (roleId)
            {
                case "deucarian.background":
                    color = Dark.Background;
                    return true;
                case "deucarian.surface":
                    color = Dark.Surface;
                    return true;
                case "deucarian.surface.raised":
                    color = Dark.SurfaceRaised;
                    return true;
                case "deucarian.primary":
                    color = Dark.Primary;
                    return true;
                case "deucarian.secondary":
                    color = Dark.Secondary;
                    return true;
                case "deucarian.accent":
                    color = Dark.Accent;
                    return true;
                case "deucarian.text.primary":
                    color = Dark.TextPrimary;
                    return true;
                case "deucarian.text.secondary":
                    color = Dark.TextSecondary;
                    return true;
                case "deucarian.text.muted":
                    color = Dark.TextMuted;
                    return true;
                case "deucarian.text.disabled":
                    color = Dark.TextDisabled;
                    return true;
                case "deucarian.success":
                    color = Dark.Success;
                    return true;
                case "deucarian.warning":
                    color = Dark.Warning;
                    return true;
                case "deucarian.error":
                    color = Dark.Error;
                    return true;
                case "deucarian.info":
                    color = Dark.Info;
                    return true;
                case "deucarian.ui.normal":
                    color = Dark.UiNormal;
                    return true;
                case "deucarian.ui.highlighted":
                    color = Dark.UiHighlighted;
                    return true;
                case "deucarian.ui.pressed":
                    color = Dark.UiPressed;
                    return true;
                case "deucarian.ui.selected":
                    color = Dark.UiSelected;
                    return true;
                case "deucarian.ui.disabled":
                    color = Dark.UiDisabled;
                    return true;
                case "deucarian.ui.focused":
                    color = Dark.UiFocused;
                    return true;
                default:
                    color = default(Color);
                    return false;
            }
        }
    }
}
